WIDTH = 1280
HEIGHT = 720

MAX_FRAME_RATE = 60

GRAY_OPACITY = 50

COLLISION_CHECK_STEPS = 8

WINNING_SCORE = 5

PADDLE_SPEED = 850
PADDLE_WIDTH = 15
PADDLE_HEIGHT = 60

SERVE_BALL_DY_MIN = -125
SERVE_BALL_DY_MAX = 125
SERVE_BALL_DX_MIN = 750
SERVE_BALL_DX_MAX = 900

REFLECT_DY_MIN = 30
REFLECT_DY_MAX = 650

REFLECT_DX_MULTIPLIER = 1.05

BALL_TERMINAL_DX = 2500

AI_UPDATE_DELAY_MIN = 0.25
AI_UPDATE_DELAY_MAX = 0.35
AI_PREDICTION_ERROR_MIN = 0.9
AI_PREDICTION_ERROR_MAX = 1.1
AI_SPEED_PREDICTION_ERROR_MAX = 0.3
AI_ANGLE_PREDICTION_ERROR_MAX = 0.25
AI_REFLECTION_ERROR_MIN = 0.15
AI_REFLECTION_ERROR_MAX = 0.25
AI_REFLECTION_REACTION_DELAY_MIN = 0.1
AI_REFLECTION_REACTION_DELAY_MAX = 0.2
AI_EDGE_POSITIONING_CHANCE = 0.3
AI_DECISIVENESS_MIN = 0.85
AI_DECISIVENESS_MAX = 1

SCREEN_SHAKE_INTENSITY = 20
SCREEN_SHAKE_DURATION = 0.1

PADDLE_HIT_PITCH_MIN = 0.35
PADDLE_HIT_PITCH_MAX = 1.25

DEBUG_PERFECT_STRONG_AI = False